kill(all) $
load("vect") $
load("nchrpl")$
load("scifac")$
load("format")$
load("cgrind")$
load("stringproc") $

frm0 (e):= format(e, %poly(Fb, Fa), %factor, gcfac) $
frm1 (e):= format(e, %poly(vx, vy, ux, uy, wx, wy), %factor, gcfac) $
co(dE, d):=frm0(factor(coeff(dE, diff(d))))         $
cross(a, b):=express(a ~ b) $

declare([ax, ay, bx, by, cx, cy], constant) $

F(a, b):= a;

(X: 1, Y: 2)$
dx(r):= p0 + px*r[X] + py*r[Y] ;
dy(r):= q0 + qx*r[X] + qy*r[Y] ;

a0: [ax, ay];
b0: [bx, by];
c0: [cx, cy];

da: [vx, vy];
db: [ux, uy];
dc: [wx, wy];

a: a0 + da;
b: b0 + db;
c: c0 + dc;

e: [
  dx(a0) = vx,
  dy(a0) = vy,

  dx(b0) = ux,
  dy(b0) = uy,

  dx(c0) = wx,
  dy(c0) = wy
] ;

de: diff(e);
v: [p0, px, py,   q0, qx, qy];
ds: linsolve(de, diff(v));
s : linsolve( e,       v) ;
ds: linsolve(de,      diff(v));

Q: ax*(cy-by)-bx*cy+by*cx+ay*(bx-cx);
ds: subst('Q, Q, ds);
s:  subst('Q, Q, s);

sxx: diff(dx([x, y]), x);
sxy: diff(dx([x, y]), y);
syx: diff(dy([x, y]), x);
syy: diff(dy([x, y]), y);

Dxx: (sxx + sxx + sxx*sxx + syx*syx)/2;
Dxy: (sxy + syx + sxx*sxy + syx*syy)/2;
Dyx: (syx + sxy + sxy*sxx + syy*syx)/2;
Dyy: (syy + syy + sxy*sxy + syy*syy)/2;
D: matrix([Dxx, Dxy], [Dyx, Dyy]) $

I1: mattrace(D);
I2: determinant(D);
I2: factor(I2);
E: F(I1, I2);

dE: subst(ds, factor(diff(E))) $
dE: expand(dE) $

dvx: gcfac((co(dE, vx)));
dvy: gcfac((co(dE, vy)));

dux: gcfac((co(dE, ux)));
duy: gcfac((co(dE, uy)));

dwx: gcfac((co(dE, wx)));
dwy: gcfac((co(dE, wy)));

fa: [dvx, dvy];
fb: [dux, duy];
fc: [dwx, dwy];

ta: cross(a, fa) ;
tb: cross(b, fb) ;
tc: cross(c, fc) ;

factor(ev(fa + fb + fc, infeval, s));
factor(ev(ta + tb + tc, infeval, s));

