kill(all) $
load("vect") $
load("nchrpl")$
load("scifac")$
load("format")$
load("cgrind")$
load("stringproc") $

frm0 (e):= format(e, %poly(Fb, Fa), %factor, gcfac) $
frm1 (e):= format(e, %poly(vx, vy, ux, uy, wx, wy), %factor, gcfac) $
co(dE, d):=frm0(factor(coeff(dE, diff(d))))         $
cross(a, b):=express(a ~ b) $

declare([ax, ay, bx, by, cx, cy], constant) $

F(a, b):=a;

dx(x, y):= p0 + px*x + py*y $
dy(x, y):= q0 + qx*x + qy*y $

e: [
  dx(ax, ay) = vx,
  dy(ax, ay) = vy,

  dx(bx, by) = ux,
  dy(bx, by) = uy,

  dx(cx, cy) = wx,
  dy(cx, cy) = wy
] $

de: diff(e);
v: [p0, px, py,   q0, qx, qy];
ds: linsolve(de, diff(v));
s : linsolve( e,       v);

ds: subst('Q, Q, ds);
s:  subst('Q, Q, s);

Dxx: diff(dx(x, y), x) + 1;
Dxy: diff(dx(x, y), y);
Dyx: diff(dy(x, y), x);
Dyy: diff(dy(x, y), y) + 1;

D: matrix([Dxx, Dxy], [Dyx, Dyy]) $
G: D . D;

I1: mattrace(G)    - 2;
I2: determinant(G) - 1;
I2: factor(I2);

E: F(I1, I2);

dE: subst(ds, factor(diff(E))) $
dE: expand(dE) $

dvx: gcfac((co(dE, vx)));
dvy: gcfac((co(dE, vy)));

dux: gcfac((co(dE, ux)));
duy: gcfac((co(dE, uy)));

dwx: gcfac((co(dE, wx)));
dwy: gcfac((co(dE, wy)));

da: [dvx, dvy];
db: [dux, duy];
dc: [dwx, dwy];

a0: [ax, ay];
b0: [bx, by];
c0: [cx, cy];

a: [ax + vx, ay + vy] $
b: [bx + ux, by + uy] $
c: [cx + wx, cy + wy] $

ta: cross(a0, da) $
tb: cross(b0, db) $
tc: cross(c0, dc) $

factor(ev(da + db + dc, infeval, s));
factor(ev(ta + tb + tc, infeval, s));
