load('scifac)$
assume(r >= 0, e >= 0);

gradef(r, x, x/r);
gradef(r, y, y/r);
gradef(r, z, z/r);

sxx: (r^2 + 2*e^2)/(r^2 + e^2)^(3/2) + x*x/(r^2 + e^2)^(3/2);
syx: y*x/(r^2 + e^2)^(3/2);
szx: z*x/(r^2 + e^2)^(3/2);

u: 1/(8*%pi*mu)*g*sxx;
v: 1/(8*%pi*mu)*g*syx;
w: 1/(8*%pi*mu)*g*szx;

Px: x * (2*r^2 + 5*e^2)/(r^2 + e^2)^(5/2);
p: 1/(8*%pi)*g*Px;

D: factor(mu*(diff(u, x, 2) + diff(u, y, 2) + diff(u, z, 2)) - diff(p, x));
gcfac(D), r = sqrt(x^2 + y^2 + z^2), factor;

p, e = 0;
[u, v, w], e = 0;

D: diff(u, x) + diff(v, y) + diff(w, z);
D, factor, r = sqrt(x^2 + y^2 + z^2);

Txxx: -Px + (diff(sxx, x) + diff(sxx, x));
Txxx, factor;
