load("vect") $
load("scifac") $

assume('p0 > 0)$
(X: 1, Y: 2, Z: 3) $
s(i, e)::=buildq([e, i], sum(e, i, 1, 3)) $

cross(a, b):= express(a ~ b) $

/* t in [0, 2*pi], p in [0, pi] */
x: 'R*cos('t)*sin('p)$
y: 'R*sin('t)*sin('p)$
z: 'R*cos('p)$

u: ['ux, 0, 'uz]$
r: [x, y, z]$
n: r / sqrt(r . r)$
/* r0: r, p = 0, t = 0$ */
r0: [x0, y0, z0]$
d: r - r0$
rad: sqrt(d . d)$

Area: integrate(integrate(dA, t, 0, 2*%pi), p, 0, p0) $
q: solve(taylor(Area0 = Area, p0, 0, 2), p0)[2];
dA: R^2*sin(p) $

fun(j):=block([e, A, B, f, i : Z],
  /* e: s(k, s(i, u[i]*d[i]*d[j]*d[k]*n[k] * dA)), */
  e: s(k, u[i]*d[i]*d[j]*d[k]*n[k] * dA),
A: ratexpand(taylor(e, p, 0, 1)),
B: ratexpand(taylor(rad^5, p, 0, 0)),
f: trigsimp(A/B),
f: integrate(integrate(f, t, 0, 2*%pi), p, 0, 'p0),
f);

fx: factor(subst([q, R = 1/h, z0 = z0 + 1/h], fun(X)));
fy: factor(subst([q, R = 1/h, z0 = z0 + 1/h], fun(Y)));
fz: factor(subst([q, R = 1/h, z0 = z0 + 1/h], fun(Z)));




