(X: 1, Y: 2, Z: 3) $

s(i, e)::=buildq([e, i], sum(e, i, 1, 3));

matchdeclare([i, j], numberp);
tellsimpafter(kd(i, j), if i = j then 1 else 0);

G: kd(i, j)/rad + d[i]*d[j]/rad^3;
d: [x, y, 0];
f: [fx, 0, fz];
rad: sqrt(d . d);

t: s(i, f[i]/A*G*dA);
t0: factor(t), j = X;

assume('r > 0);
t0: trigsimp(t0), x = 'r*cos('p), y = 'r*sin('p), dA = r, A : %pi*R^2;

integrate(integrate(t0, p, 0, 2*%pi), r, 0, R);

/* [3*fx, 0, 2*fz]/R; */