
rr(vr, vp, vt):= - p + 2*mu*diff(vr, r);
pp(vr, vp, vt):= - p + 2*mu*(1/(r*sin(t)) * diff(vp, p) + diff(vr, r) + diff(vt, t)*cot(t)/r);
tt(vr, vp, vt):= - p + 2*mu*(1/r*diff(vt, t) + vr/r);
rp(vr, vp, vt):= mu * (1/r + diff(vr, t) + diff(vt, r) - vt/r);
tp(vr, vp, vt):= mu * (1/(r*sin(t)) * diff(vt, p) + 1/r*diff(vp, t) - vp*cot(t)/r);
pr(vr, vp, vt):= mu * (diff(vp, r) + 1/(r*sin(t)) * diff(vr, p) - vp/r);

