(X: 1, Y: 2, Z: 3) $
s(i, e)::=buildq([e, i], sum(e, i, 1, 3))$
matchdeclare([i, j], numberp)$
tellsimpafter(kd(i, j), if i = j then 1 else 0)$

a: [0, 0, 0]$
b: [1, 0, 0]$
c: ['cx, 'cy, 0]$

/* u in [0, 1], v in [0, 1 - u] */
r: a + 'u*(b - a) + 'v*(c - a);

x: r[X];
y: r[Y];
z: r[Z];

J: matrix([diff(x, 'u), diff(x, 'v)], [diff(y, 'u), diff(y, 'v)]);
dA: determinant(J);

int(e):=integrate(integrate(e, 'v, 0, 1 - 'u), 'u, 0, 1);
int(dA);

r0: r, u = 0, v = 0;
d: r - r0;
rad: sqrt(d . d);
u: ['ux, 'uy, 'uz] $
n: [0, 0, 'nz] $

j: Z;
e: s(k, s(i, u[i]*d[i]*d[j]*d[k]*n[k] * dA));

assume(u < 1,  u > 0, cx > 0, cy > 0);
integrate(e, 'v, 0, 1 - 'u);
