load("co/vec.mac")$
load("co/tri.mac")$
load("vect")$
cross(a, b):=express(a ~ b) $
vabs(a):= sqrt(a . a) $

vec_ini(a);
vec_ini(b);
vec_ini(c);

/* u in [0, 1], v in [0, 1 - u] */
r: a + 'u*(b - a) + 'v*(c - a);
[x, y, z]: r;

ru: diff(r, 'u);
rv: diff(r, 'v);

dA: vabs(cross(ru, rv));
int1(e):=integrate(e, 'v, 0, 1 - 'u)$
int(e):=integrate(integrate(e, 'v, 0, 1 - 'u), 'u, 0, 1);

expand(int(dA)/tri_area(a, b, c));

int1(1/x);