#include <stdio.h>
#include <stdlib.h>
#include <real.h>
#include <co/argv.h>
#include <co/array.h>
#include <co/ten.h>
#include <co/edg.h>
#include <co/err.h>
#include <co/he.h>
#include <co/green/3wall.h>
#include <co/vec.h>
#include <co/memory.h>
#include <co/macro.h>
#include <co/y.h>

#define FMT CO_REAL_OUT
static real pi = 3.141592653589793115997964;

static char me[] = "green3wall/grid";
static void
usg()
{
    fprintf(stderr, "%s [-w wall] x0 y0 z0 gx gy gz < OFF\n", me);
    exit(1);
}

int
main(int argc, const char **argv)
{
    He *he;
    Green3Wall *green;
    real *x, *y, *z;
    real a[3], b[3], g[3];
    real u[3];
    real w;
    real lo;
    real hi;
    real dx;
    real *ux;
    real *uy;
    real *uz;
    real *distance;
    int nx;
    int n;
    int i;
    int j;
    int k;
    int l;
    Ten ten;
    enum {X, Y, Z};
    FILE *f;
    USED(argc);

    w = 0;
    lo = -2;
    hi = 2;
    nx = 100;
    n = (nx + 1)*(nx + 1)*(nx + 1);
    dx = (hi - lo) / nx;
    MALLOC3(n, &ux, &uy, &uz);
    MALLOC(n, &distance);
    err_set_ignore();
    while (*++argv != NULL && argv[0][0] == '-')
	switch (argv[0][1]) {
	case 'h':
	    usg();
	    break;
	case 'w':
	    argv++;
	    if (argv[0] == NULL) {
		fprintf(stderr, "%s: -w needs an argument\n", me);
		exit(1);
	    }
	    w = atof(argv[0]);
	    break;
	default:
	    fprintf(stderr, "%s: unknown option '%s'\n", me, argv[0]);
	    exit(1);
	}
    y_inif(stdin, &he, &x, &y, &z);

    if (vec_argv(&argv, b) != CO_OK) {
	fprintf(stdin, "%s: fail to read vector\n", me);
	exit(1);
    }
    if (vec_argv(&argv, g) != CO_OK) {
	fprintf(stdin, "%s: fail to read vector\n", me);
	exit(1);
    }
    if (*argv != NULL) {
	fprintf(stdin, "%s: too many arguments\n", me);
	exit(1);
    }

    green3_wall_ini(he, w, &green);
    for (k = l = 0; k < nx + 1; k++)
      for (j = 0; j < nx + 1; j++)
	for (i = 0; i < nx + 1; i++, l++) {
	  vec_ini(lo + dx * i, lo + dx * j, lo + dx * k, a);
	  green3_wall_s(green, a, b, &ten);
	  ten_vec(&ten, g, u);
	  vec_scale(1/(8*pi), u);
	  ux[l] = u[X];
	  uy[l] = u[Y];
	  uz[l] = u[Z];
	  distance[l] = edg_abs(a, b);
	}
    f = stdout;
    fprintf(f, "# vtk DataFile Version 2.0\n"
            "generated by %s\n"
            "ASCII\n"
            "DATASET STRUCTURED_POINTS\n"
            "DIMENSIONS %d %d %d\n"
            "ORIGIN %.16g %.16g %.16g\n"
            "SPACING %.16g %.16g %.16g\n",
            me, nx + 1, nx + 1, nx + 1, lo, lo, lo, dx, dx, dx);
    fprintf(f, "POINT_DATA %d\n", n);
    fputs("VECTORS v double\n", f);
    for (i = 0; i < n; i++)
        fprintf(f, FMT " " FMT " " FMT "\n", ux[i], uy[i], uz[i]);
    fputs("SCALARS distance double\n", f);
    fputs("LOOKUP_TABLE DEFAULT\n", f);
    for (i = 0; i < n; i++)
      fprintf(f, FMT "\n", distance[i]);
    
    green3_wall_fin(green);
    FREE3(ux, uy, uz);
    FREE(distance);
    y_fin(he, x, y, z);
}
