load("nchrpl")$

matchdeclare(x, all) $
defrule(r_sq0, x^2, sq(x)) $
defrule(r_sq1, 1/x^2, 1/sq(x)) $
rsq(e):=apply1(e, r_sq0, r_sq1) $

M: matrix([px, py], [0, qy])$
e: [
  (M.[bx,  0])[1, 1] = ux,
  (M.[cx, cy])[1, 1] = wx,
  (M.[cx, cy])[2, 1] = wy] $
s: linsolve(e, listofvars(M)) $

D: M . transpose(M) $
al: determinant(M) - 1 $
be: 1/(2*determinant(M))*(mattrace(D) - 2*determinant(M)) $

grind(s);
grind('al = al);
grind('be = rsq(be));
