#!/bin/sh

. co.util
prog=co.x

lo="$1"; shift
hi="$1"; shift

r=
for i
do
	case "$i" in
		*.off) r="$i"; break
	esac
done
if test -z "$r"
then err "no off file among arguments"
fi

co.geomview -p  "co.xcolor $r $lo $hi" "$@"
