#!/bin/sh
set -eu

norm () {
    sort | sed 's,^\.\/,,g'
}

real0 () {
    grep -q '[ \t]*#[ \t]*include[ \t]*\"real\.h\"' "$1"
}

real () {
    while read f
    do  if real0 "$f"
        then printf "%s\n" "$f"
        fi
    done
}

nreal () {
    while read f
    do  if ! real0 "$f"
        then printf "%s\n" "$f"
        fi
    done
}

format () {
   awk -v v="$1" '
   BEGIN { printf "%s = \\\n", v }
   {
       printf "%s\\\n", $0
   }
   END { printf "%s", "\n" }
'
}

name () {
    s=$1; shift
    sed -e "s,\.c$,.$s,1" -e "s,\.c\.m4$,.$s,1"
}

src () { find . -name '*.c' -or -name '*.c.m4' | sort ; }
hdr () { find . -name '*.h' | sort ; }

hdr | norm |                    format H     > make/hdr.mk
src | norm | nreal | name o   | format O     > make/obj.mk
src | norm |  real | name s.o | format O_S  >> make/obj.mk
src | norm |  real | name d.o | format O_D  >> make/obj.mk
src | norm |  real | name l.o | format O_L  >> make/obj.mk

../tool/dep `src | norm | nreal` | ../tool/fmt   o >  make/dep.mk
../tool/dep `src | norm |  real` | ../tool/fmt s.o >> make/dep.mk
../tool/dep `src | norm |  real` | ../tool/fmt d.o >> make/dep.mk
../tool/dep `src | norm |  real` | ../tool/fmt l.o >> make/dep.mk
