.POSIX:
.SUFFIXES:
.SUFFIXES: .c .c.m4 .d.o .f .f90 .h .h.m4 .l.o .o .s.o
include ../conf.mk

L = lib$P_s.a lib$P_d.a lib$P_l.a

include make/hdr.mk
include make/obj.mk
include make/rules.mk
include make/dep.mk
