#!/bin/sh

awk -v suffix="$1" '
BEGIN {
    RS = ""
    FS = "\n"

    inc["s.o"] = "co/prec/s"
    inc["d.o"] = "co/prec/d"
    inc["l.o"] = "co/prec/l"
}

{
    write($1)
}

function write(f)
{
    sub(/.c$/, "." suffix, f)
    sub(/^.\//, "", f)
    print f ":\\"
    for (i = 2; i <= NF; i++)
        print transform($i) "\\"
    print ""
}

function transform(f)
{
    if (eq(f, "real.h"))
        return inc[suffix] "/real.h"
    else
        return f
}

function eq(a, b)
{
    return "" a == "" b
}
'
