#!/bin/sh

VERSION_CONTROL=none
export VERSION_CONTROL

exec indent \
     --pointer-align-right\
     --k-and-r-style\
     --blank-lines-after-declarations\
     --procnames-start-lines\
     --no-tabs\
     --tab-size 4\
     "$@"
