load("scifac") $
load("format") $

/* [a, b], [I1, I2]: invariants of strain rate tensor
   [e11, e22], [x, y]: eigen values of  strain rate tensor
   l1, l2: local principle stretches?
*/

/*
e: [x + y = a, x * y = b];
s: solve(e, [x, y]);

l1: sqrt(1 + 2*x);
l2: sqrt(1 + 2*y);

e11: (l1^2 - 1)/2;
e22: (l2^2 - 1)/2;

I1: e11 + e22;
I2: e11*e22;

al: e11*e22 - 1;
be: (e11 - e22)^2/(2*e11*e22); */

I1s: 2*'I1;
I2s: 4*'I2 + 2*'I1;

W: Ks*(I1s^2/2 + I1s - I2s)/4 + Ka/8*I2s;
W: factor(W);

W: format(W, %poly('I1, 'I2), %factor);

diff(W, 'I1);
diff(W, 'I2);