%wendland6_2d: (78/(7*%pi));
pow(a, b):=a^b;
wendland6_w0(q):=pow(1-q,8)*(32*pow(q,3)+25*pow(q,2)+8*q+1);
wendland6_dw0(q):=22*pow(q-1,7)*q*(16*pow(q,2)+7*q+1);
wendland6_w2(c, x):=block([q: x/c], %wendland6_2d * wendland6_w0(q) / (c*c));
wendland6_dw2(c, x):= block([q: x/c], %wendland6_2d* wendland6_dw0(q) / (c*c*c));

%it(e):=integrate(e, 't, 0, 2*%pi);
%ip(e):=integrate(e, 'p, 0, %pi);
%ir(e):=integrate('r^2*sin('p)*e, 'r, 0, 1);
i3(e):=%it(%ip(%ir(e)));