S = ../..
include $S/conf.mk

M = \
area.mac\
array.mac\
curv.mac\
ddih.mac\
dedg.mac\
dih.mac\
dtri2.mac\
dtri.mac\
dvec.mac\
edg2.mac\
edg.mac\
err.mac\
he.mac\
kernel.mac\
loop.mac\
normal.mac\
off.mac\
punto.mac\
ten.mac\
tri2.mac\
tri.mac\
util.mac\
vec2.mac\
vec.mac\

install: $M; co.install $M $(MAXIMA_HOME)/$P
clean:
test:

.PHONY: install clean test
