S = ../..
include $S/conf.mk

M = \
dih.mac\
ddih.mac\
dedg.mac\
dvec.mac\
dtri.mac\
edg.mac\
err.mac\
co.mac\
off.mac\
tri.mac\
loop.mac\
punto.mac\
ten.mac\
vec.mac\
util.mac

install: $M; co.install $M $(MAXIMA_HOME)/$P
clean:
test:

.PHONY: install clean test
