load("stringproc") $

file: "~/0.off";

s: openr(file);
l: readline(s);
l: readline(s);

[v, t, e]: map(parse_string, split(l));

ver: make_array('any, v, 3) $
read_array(s, ver);

tri: make_array('any, t, 1 + 3) $
read_array(s, tri);

close(s);

[ver[0,0], ver[0,1], ver[0,2]];
[ver[v - 1,0], ver[v - 1,1], ver[v - 1,2]];

[tri[0,1], tri[0,2], tri[0,3]];
[tri[t - 1,1], tri[t - 1,2], tri[t - 1,3]];

