load("partition") $

%s:[
u = W * q,
v = q * z0,
w = q * z] $

%d: [
Ap = u + sinh(u)*exp(-u),
Am = u - sinh(u)*exp(-u),
Bp = u + cosh(u)*exp(-u),
Bm = u - cosh(u)*exp(-u),
Cp = u*(1 + u) + sinh(u)*exp(-u),
Cm = u*(1 + u) - sinh(u)*exp(-u),
Dp = u*(1 + u) + cosh(u)*exp(-u),
Dm = u*(1 + u) - cosh(u)*exp(-u),
Ep = 1/(sinh(u)*cosh(u) + u),
Em = 1/(sinh(u)*cosh(u) - u)] $

tnn:
  Em*(-v*cosh(v) + Bp*sinh(v))*w*cosh(w)
  + Ep*(-v*sinh(v) + Ap*cosh(v))*w*sinh(w)
  + Ep*(Ap*v*sinh(v) - Cp*cosh(v))*cosh(w)
  + Em*(Bp*v*cosh(v) - Dp*sinh(v))*sinh(w)$

tnp:
  Em*(v*sinh(v) - Am*cosh(v))*w*cosh(w)
  + Ep*(v*cosh(v) - Bm*sinh(v))*w*sinh(w)
  + Ep*(-Ap*v*cosh(v) + u^2*sinh(v))*cosh(w)
  + Em*(-Bp*v*sinh(v) + u^2*cosh(v))*sinh(w)$

tpn:
  Ep*(-v*sinh(v) + Ap*cosh(v))*w*cosh(w)
  + Em*(-v*cosh(v) + Bp*sinh(v))*w*sinh(w)
  + Em*(Am*v*cosh(v) - u^2*sinh(v))*cosh(w)
  + Ep*(Bm*v*sinh(v) - u^2*cosh(v))*sinh(w)$

tpp:
  Ep*(v*cosh(v) - Bm*sinh(v))*w*cosh(w)
  + Em*(v*sinh(v) - Am*cosh(v))*w*sinh(w)
  + Em*(-Am*v*sinh(v) + Cm*cosh(v)
      -2*u*tanh(u)*cosh(v))*cosh(w)
    + Ep*(-Bm*v*cosh(v) + Dm*sinh(v)
      - 2*u*coth(u)*sinh(v))*sinh(w)$

rpp:
  (-2*exp(-u)*cosh(v)/cosh(u))*cosh(w)
  +(-2*exp(-u)*sinh(v)/sinh(u))*sinh(w)$


tpp: exponentialize(ev(tpp, %d)) $
tpp: expand(tpp) $

tpp: subst(log(W) - u, w, tpp) $
tpp: subst(log(V) - u, v, tpp) $
tpp: subst(log(U), u, tpp) $
tpp: expand(tpp);
