declare([d, s], linear);
dotdistrib: true;
dotassoc: false;

iso(e, v):=second(partition(e, d(v))) $

matchdeclare([x, y], all);
tellsimp(d(lp . nn),   lp.d(nn) + nn.d(lp));
tellsimp(d(lp . lp),   2*lp.d(lp));
tellsimp(d(n(x)), dn . d(x));
tellsimp(d(s(x)), d(x));
tellsimp(d(ec*tb), d(ec)*tb + ec.d(tb));
tellsimp(d(eb*tc), d(eb)*tc + eb.d(tc));
tellsimp(d(ang*u), d(u)*ang + u.d(ang));

m: s(ang*u);
nn: n(m);

lp0: s(tb*ec + tc*eb);
tellsimp(d(lp), d(lp0));

H: lp . lp;

dH: d(H);
dH: ratexpand(subst('nn, n(m), dH));

iso(dH, u);
iso(dH, ang);
iso(dH, tb);
iso(dH, eb);
