#!/bin/sh
set -eu

norm () {
    sort | sed 's,^\.\/,,g'
}

real0 () {
    grep -q '[ \t]*#[ \t]*include[ \t]*<real\.h>' "$1"
}

real () {
    while read f
    do  if real0 "$f"
	then printf "%s\n" "$f"
	fi
    done
}

nreal () {
    while read f
    do  if ! real0 "$f"
	then printf "%s\n" "$f"
	fi
    done
}

format () {
   xargs -n5 | awk -v v="$1" '
   BEGIN { printf "%s = \\\n", v }
   {   if (NR > 1) printf "%s", " \\\n"
       printf "%s", $0
   }
   END { printf "%s", "\n" }
'
}

name_o () ( sed 's,\.c$,.o,g' )
name_s () ( sed 's,\.c$,.s.o,g' )
name_d () ( sed 's,\.c$,.d.o,g' )
name_l () ( sed 's,\.c$,.l.o,g' )

find alg -name '*.h'  | norm |                  format H     > make/hdr.mk
find .  -name '*.c'  | norm | nreal | name_o | format O     > make/obj.mk
find .  -name '*.c'  | norm |  real | name_s | format O_S  >> make/obj.mk
find .  -name '*.c'  | norm |  real | name_d | format O_D  >> make/obj.mk
find .  -name '*.c'  | norm |  real | name_l | format O_L  >> make/obj.mk
