include ../conf.mk
CO_S_CFLAGS = `co.conf --cflags s`
CO_D_CFLAGS = `co.conf --cflags d`
CO_L_CFLAGS = `co.conf --cflags l`

P = alg
L = libalg_s.a libalg_d.a libalg_l.a

include make/hdr.mk
include make/obj.mk
include make/rules.mk
include make/dep.mk
