#!/usr/bin/awk -f

BEGIN {
    me = "name"
    print "static const char *TagName[] = {"
}

{
    tag = $1
    printf "    \"%s\",\n", tag
}

END {
    print "};"
}

function err(a, b, c, d, e)
{
    printf "%s: " a "\n", me, b, c, d, e | "cat >&2"
    exit(2)
}

function integerp(x)
{
    return x ~ /^[1-9][0-9]*$/
}
