#!/usr/bin/awk -f

BEGIN {
    me = "type"
    print "static int TagType[] = {"
}

{
    type = $4
    printf "    TAG_%s,\n", type
}

END {
    print "};"
}

function err(a, b, c, d, e)
{
    printf "%s: " a "\n", me, b, c, d, e | "cat >&2"
    exit(2)
}

function integerp(x)
{
    return x ~ /^[1-9][0-9]*$/
}
