load("stringproc")$

load("he/off.mac")$
load("he/util.mac")$
load("he/he.mac")$
load("he/vec.mac")$
load("he/tri.mac")$
load("he/util.mac")$
load("he/loop.mac")$

f: "data/ring.off";
he: he(f) $

i: 0;
n: loop_ring(he, i, s) + 1;
alloc(n, be, th);
(Al: 0,
  loop_ring(he, i, Al += be[s]: tri_angle(c, a, b)));

for i: 0 thru n - 1 do be[i]: 2*%pi*be[i]/Al;

th[0]: 0;
for i: 1 thru n - 1 do th[i]: th[i - 1] + be[i];

