load("co/vec.mac") $
load("co/dedg.mac") $
load("co/edg.mac") $
load("co/tri.mac") $
load("co/dtri.mac") $

vec_any(a); vec_any(b); vec_any(c);
vec_any(u); vec_any(v); vec_any(w);

tri_edg_area(a, b, c), numer;
tri_beta(a, b, c, u, v, w), numer;

vec_arg(a, b, c, u, v, w);

vec_arg(a, b, c);

vec_ini(a); vec_ini(b); vec_ini(c);
[da, db, dc]: dtri_edg_area(a, b, c), numer;

radcan(dtri_edg_area(a, b, c)[1][3] - jacobian([tri_edg_area(a, b, c)], a)[1,3]);
