#!/bin/sh

case "$1" in
    -s) args="$1"
         shift
         ;;
    -t) args="$1"
        shift
        ;;
    -*) printf >&2 "unknown option: '%s'\n" "$1"
        exit 2
        ;;
esac

for i
do
    co.eigenvector "$args" < "$i" | awk '{if ($3<0) {$1=-$1; $3=-$3;} print atan2($3, $1)/3.141592653589793}'
    if test $? -ne 0
    then
        exit 2
    fi
done
